# Generated by Django 4.0.3 on 2022-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('year_published', models.IntegerField()),
                ('imdbId', models.CharField(max_length=100, unique=True)),
                ('imdbRating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
